# Generated by Django 2.2 on 2020-03-22 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='文章创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='文章更新时间')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='文章浏览量')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ('-created',),
            },
        ),
    ]
